### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by tsoufakis** [tsoufakis/kareljs#13]
(node:1) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:832:32)
    at /app/node_modules/mongoose/lib/index.js:345:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/app/src/api.js:11:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/src/server.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by tsoufakis** [comment]
resolved with 6.4
